name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: Setup Docker on macOS          
      uses: douglascamata/setup-docker-macos-action@v1-alpha
            
    - name: Setup upterm session
      uses: fawazahmed0/action-debug-vscode@main
